### ISSUE TITLE
Download the Singularity to the right folder

### ISSUE THREAD

**Issue by chuliangcui** [jpetucci/RNABindRPlus-Local#1]
Hi, for downloading the Singularity, the README said `Download the Singularity container under the release menu assets (rnabindrplus-local.sif) into $RNABINDRPLUS_HOME`. I didn't find the file `rnabindrplus-local.sif`. Should I install into `$RNABINDRPLUS_HOME` folder? And why I didn't find the `rnabindrplus-local.sif` file?
Thanks!

**Comment by jpetucci** [comment]
@chuliangcui, you should be able to access the singularity file here: https://github.com/jpetucci/RNABindRPlus-Local/releases/download/v1.0.1-alpha/rnabindrplus-local.sif . Please let me know if you have any issues with that link.

Yes, you should put the Singularity container into the directory you define as RNABINDRPLUS_HOME.

**Comment by chuliangcui** [comment]
> @chuliangcui, you should be able to access the singularity file here: https://github.com/jpetucci/RNABindRPlus-Local/releases/download/v1.0.1-alpha/rnabindrplus-local.sif . Please let me know if you have any issues with that link.
> 
> Yes, you should put the Singularity container into the directory you define as RNABINDRPLUS_HOME.

Thanks! It works now!
