### ISSUE TITLE
Final Predictions folder 404 – Not Found

### ISSUE THREAD

**Issue by chuliangcui** [jpetucci/RNABindRPlus-Local#2]
Hi I have successfully installed the software locally and can open http://localhost:8080/RNABindRPlus/.
```
Your job (2022-3-25-15-39.97.2ix1m_A) is now running
View output files here: [Output](http://localhost:8080/RNABindRPlus/uploadData/2022-3-25-15-39.97.2ix1m_A)
View the running log file (manually refresh that page for updates): [Main Log file](http://localhost:8080/RNABindRPlus/uploadData/LOGs/2022-3-25-15-39.97.2ix1m_A.txt)
When the job finishes, these main output files will be available:
[Final Predictions](http://localhost:8080/RNABindRPlus/uploadData/2022-3-25-15-39.97.2ix1m_A/finalpredictionsFor2022-3-25-15-39.97.2ix1m_A.txt)
[Homologs](http://localhost:8080/RNABindRPlus/uploadData/2022-3-25-15-39.97.2ix1m_A/homologsFor2022-3-25-15-39.97.2ix1m_A.txt)
[Statistics](http://localhost:8080/RNABindRPlus/uploadData/2022-3-25-15-39.97.2ix1m_A/statistics_2022-3-25-15-39.97.2ix1m_A.txt)
```
However the Final Predictions folder is not avaliable.

```
Type Status Report

Message The requested resource [/RNABindRPlus/uploadData/2022-3-25-15-39.97.2ix1m_A/finalpredictionsFor2022-3-25-15-39.97.2ix1m_A.txt] is not available

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

```
Also the main website http://ailab-projects2.ist.psu.edu/RNABindRPlus/, I can open it but if I can't submit a job. After clicking "submit", a blank page will appear "http://ailab-projects2.ist.psu.edu/RNABindRPlus/cgi-bin/predict.cgi"

**Comment by jpetucci** [comment]
@chuliangcui, http://ailab-projects2.ist.psu.edu/RNABindRPlus/ was down for maintenance. It is back up now. Please let me know if you continue to have any issues.

On the machine where you have this installed, what are the contents of (run the ls command)
$RNABINDRPLUS_HOME/webapps/RNABindRPlus/uploadData/2022-3-25-15-39.97.2ix1m_A ?

**Comment by chuliangcui** [comment]
@jpetucci Nice! I found my final results there! Question is why the link is not responding? Should I wait or in the future should I always go to the $RNABINDRPLUS_HOME/webapps/RNABindRPlus/uploadData/ folder?
Thanks!

**Comment by jpetucci** [comment]
@chuliangcui , the final prediction file will not be available until the run completes. You can click the first "Output" link and periodically refresh until the prediction file shows up indicating the run in complete.
